[Feature] Criar código de conduta
ufrpe-devs/comunidade pull request #49
Opened 2021-09-15 01:07 UTC by ThalesGabriel

2021-09-15 02:54 UTC, SteffanoP commented
Vou ver se dou uma olhada amanhã @ThalesGabriel, lembra que teu commit não tá configurado para tua conta do GitHub, provavelmente não conseguiu conectar o email do commit aos teus emails do GitHub.

2021-09-16 00:42 UTC, ThalesGabriel commented
Sim sim, eu tinha usado a máquina do trampo pra fazer, daí unica coisa que fiz foi cadastrar a chave ssh aqui mas o email dela é diferente do github

2021-09-16 02:12 UTC, SteffanoP submitted a review, later dismissed
@ThalesGabriel Achei muito massa a ideia de seguir o Contributor Covenant Guide para montar o nosso Guia de Contribuição, muito obrigado por estar ajudando na construção de nossa comunidade. Adoraria contar com você pra completar um pouco do nosso Código de Conduta, acabei de ver aqui e acho interessante completar o nosso `CODE_OF_CONDUCT.md` com o próprio código de conduta do Contributor Covenant. Logo acho massa que você utilizasse esse [documento aqui](https://www.contributor-covenant.org/pt-br/version/2/0/code_of_conduct/code_of_conduct.md).

BTW, também verifiquei que está faltando o título (Header h1) do documento.

2021-09-16 02:12 UTC, SteffanoP commented on CODE_OF_CONDUCT.md
> +<br/>
Rapaz, acho que essa linha não é necessária, visto que no Markdown do GitHub ele já cria uma linha de separação do Header

2021-09-16 02:12 UTC, SteffanoP commented on CODE_OF_CONDUCT.md
> +<br/>
O mesmo daqui na questão da linha do Header

2021-09-16 02:12 UTC, SteffanoP commented on README.md
> +
Acho que na ordem do `Readme.md` pode ser a seguinte:

- Quem somos?
- Como participar?
- **Código de Conduta**

Inclusive, acho que até seria interessante mudar o Header para algo como: `Nosso Guia de Conduta` e pode até colocar um emoji para que o título fique harmonioso.

2021-09-16 14:08 UTC, ItaloSa requested changes

2021-09-16 14:08 UTC, ItaloSa commented on CODE_OF_CONDUCT.md
> +- Quando solicitada sua ajuda, procure sempre estar disposto a ajudar, mesmo que procurando alguém que tenha mais conhecimento sobre.
Quando tiver os tópicos assim coloca `;` em todos e somente no último o `.`

2021-09-16 14:08 UTC, ItaloSa commented on CODE_OF_CONDUCT.md
> +- Outra conduta que poderia ser razoavelmente considerada inadequada em um ambiente profissional
O comentário anterior se aplica aqui!

2021-09-21 23:12 UTC, SteffanoP commented
@ThalesGabriel devido a urgência em implementar essa Pull Request, eu vou estar assumindo a PR, para dar um avanço nesse feature

2021-09-21 23:57 UTC, ItaloSa requested changes
Faltou somente um comentário

2021-09-21 23:57 UTC, ItaloSa commented on README.md
> +
☝️

2021-09-22 00:09 UTC, SteffanoP commented
O Merge não foi verificado, idk why, porém foi proposital para atualizar o `README.md`.

2021-09-22 00:11 UTC, ItaloSa approved these changes
LGTM!

2021-09-22 00:12 UTC, merged